definitions:
  main.addTodoItemDto:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  models.TodoItem:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /add:
    post:
      consumes:
      - application/json
      description: adds todolist item
      parameters:
      - description: todo item for add
        in: body
        name: todoItem
        required: true
        schema:
          $ref: '#/definitions/main.addTodoItemDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Add todo item
      tags:
      - TodoItem
  /get/{id}:
    get:
      consumes:
      - application/json
      description: gets todolist item
      parameters:
      - description: id for search todo item
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TodoItem'
      summary: Get todo item by id
      tags:
      - TodoItem
  /update:
    put:
      consumes:
      - application/json
      description: updates todolist item
      parameters:
      - description: todo item for update
        in: body
        name: todoItem
        required: true
        schema:
          $ref: '#/definitions/models.TodoItem'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update todo item
      tags:
      - TodoItem
swagger: "2.0"
